Sangita assignment1
automationtestplanet/CoreJava_Aug2024 pull request #3
Opened 2024-09-10 02:40 UTC by sangita0202

2024-09-10 03:01 UTC, automationtestplanet requested changes

2024-09-10 03:01 UTC, automationtestplanet commented on src/assignments/sangita/Assignment1.java
> +            return Arrays.equals(c1,c2);
convert char array to string then compare

2024-09-13 03:49 UTC, rajuchelle approved these changes

2024-09-13 03:50 UTC, automationtestplanet approved these changes

2024-09-14 01:43 UTC, merged